2022-05-19 18:51:10,992 ERROR: Exception on /edit_profile [POST] [in /Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/app/routes.py", line 83, in edit_profile
    db.session.commit()
  File "<string>", line 2, in commit
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3367, in flush
    self._flush(objects)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3507, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3467, in _flush
    flush_context.execute()
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
    _emit_update_statements(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
    c = connection._execute_20(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/Users/m.palanisamy/Projects/Flask-Learning/Microblog/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('mahi', '', 4)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
